[package]
name = "penplot"
version = "0.1.0"
authors = ["May Lawver <may@maycod.es>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.12"
